/**
 * GENERATED by solana/scripts/launchpad/idl-offsets.mjs from solana/sdk/idl/vicinity_launchpad.json and
 * solana/idls/dynamic_bonding_curve.json: byte offsets of the account fields src/sol/dbc.js decodes, the program constants
 * and the error tables. Do not edit: re-run the script (solana/tests-launchpad/15-worker-builder.test.mjs fails when stale).
 */
export const LAYOUT = {
 "generatedFrom": {
  "launchpad": "vicinity_launchpad 0.1.0",
  "dbc": "dynamic_bonding_curve 0.2.1"
 },
 "Coin": {
  "discriminator": [
   215,
   195,
   53,
   238,
   217,
   196,
   213,
   51
  ],
  "size": 243,
  "fields": {
   "city_id": {
    "at": 8,
    "type": "u64",
    "size": 8
   },
   "founder": {
    "at": 16,
    "type": "pubkey",
    "size": 32
   },
   "mint": {
    "at": 48,
    "type": "pubkey",
    "size": 32
   },
   "quote_mint": {
    "at": 80,
    "type": "pubkey",
    "size": 32
   },
   "dbc_config": {
    "at": 112,
    "type": "pubkey",
    "size": 32
   },
   "dbc_pool": {
    "at": 144,
    "type": "pubkey",
    "size": 32
   },
   "launched_at": {
    "at": 176,
    "type": "i64",
    "size": 8
   },
   "holders_accrued": {
    "at": 184,
    "type": "u64",
    "size": 8
   },
   "holders_forwarded": {
    "at": 192,
    "type": "u64",
    "size": 8
   },
   "founder_accrued": {
    "at": 200,
    "type": "u64",
    "size": 8
   },
   "founder_claimed": {
    "at": 208,
    "type": "u64",
    "size": 8
   },
   "founder_paid_out": {
    "at": 216,
    "type": "u64",
    "size": 8
   },
   "payout_seq": {
    "at": 224,
    "type": "u64",
    "size": 8
   },
   "last_payout_at": {
    "at": 232,
    "type": "i64",
    "size": 8
   },
   "bump": {
    "at": 240,
    "type": "u8",
    "size": 1
   },
   "holders_pot_bump": {
    "at": 241,
    "type": "u8",
    "size": 1
   },
   "founder_vault_bump": {
    "at": 242,
    "type": "u8",
    "size": 1
   }
  }
 },
 "Launchpad": {
  "discriminator": [
   247,
   20,
   16,
   242,
   203,
   38,
   169,
   160
  ],
  "size": 171,
  "fields": {
   "admin": {
    "at": 8,
    "type": "pubkey",
    "size": 32
   },
   "pending_admin": {
    "at": 40,
    "type": "pubkey",
    "size": 32
   },
   "payout_authority": {
    "at": 72,
    "type": "pubkey",
    "size": 32
   },
   "payout_destination": {
    "at": 104,
    "type": "pubkey",
    "size": 32
   },
   "rewards_program": {
    "at": 136,
    "type": "pubkey",
    "size": 32
   },
   "launches_paused": {
    "at": 168,
    "type": "bool",
    "size": 1
   },
   "payouts_paused": {
    "at": 169,
    "type": "bool",
    "size": 1
   },
   "bump": {
    "at": 170,
    "type": "u8",
    "size": 1
   }
  }
 },
 "LaunchConfig": {
  "discriminator": [
   18,
   161,
   9,
   224,
   102,
   145,
   29,
   94
  ],
  "size": 106,
  "fields": {
   "dbc_config": {
    "at": 8,
    "type": "pubkey",
    "size": 32
   },
   "quote_mint": {
    "at": 40,
    "type": "pubkey",
    "size": 32
   },
   "migration_quote_threshold": {
    "at": 72,
    "type": "u64",
    "size": 8
   },
   "trade_fee_numerator": {
    "at": 80,
    "type": "u64",
    "size": 8
   },
   "pool_creation_fee": {
    "at": 88,
    "type": "u64",
    "size": 8
   },
   "enabled": {
    "at": 96,
    "type": "bool",
    "size": 1
   },
   "added_at": {
    "at": 97,
    "type": "i64",
    "size": 8
   },
   "bump": {
    "at": 105,
    "type": "u8",
    "size": 1
   }
  }
 },
 "VirtualPool": {
  "discriminator": [
   213,
   224,
   5,
   209,
   98,
   69,
   119,
   92
  ],
  "size": 424,
  "fields": {
   "volatility_tracker.last_update_timestamp": {
    "at": 8,
    "type": "u64",
    "size": 8
   },
   "volatility_tracker.padding": {
    "at": 16,
    "type": "u8",
    "size": 1,
    "count": 8
   },
   "volatility_tracker.sqrt_price_reference": {
    "at": 24,
    "type": "u128",
    "size": 16
   },
   "volatility_tracker.volatility_accumulator": {
    "at": 40,
    "type": "u128",
    "size": 16
   },
   "volatility_tracker.volatility_reference": {
    "at": 56,
    "type": "u128",
    "size": 16
   },
   "config": {
    "at": 72,
    "type": "pubkey",
    "size": 32
   },
   "creator": {
    "at": 104,
    "type": "pubkey",
    "size": 32
   },
   "base_mint": {
    "at": 136,
    "type": "pubkey",
    "size": 32
   },
   "base_vault": {
    "at": 168,
    "type": "pubkey",
    "size": 32
   },
   "quote_vault": {
    "at": 200,
    "type": "pubkey",
    "size": 32
   },
   "base_reserve": {
    "at": 232,
    "type": "u64",
    "size": 8
   },
   "quote_reserve": {
    "at": 240,
    "type": "u64",
    "size": 8
   },
   "protocol_base_fee": {
    "at": 248,
    "type": "u64",
    "size": 8
   },
   "protocol_quote_fee": {
    "at": 256,
    "type": "u64",
    "size": 8
   },
   "partner_base_fee": {
    "at": 264,
    "type": "u64",
    "size": 8
   },
   "partner_quote_fee": {
    "at": 272,
    "type": "u64",
    "size": 8
   },
   "sqrt_price": {
    "at": 280,
    "type": "u128",
    "size": 16
   },
   "activation_point": {
    "at": 296,
    "type": "u64",
    "size": 8
   },
   "pool_type": {
    "at": 304,
    "type": "u8",
    "size": 1
   },
   "is_migrated": {
    "at": 305,
    "type": "u8",
    "size": 1
   },
   "is_partner_withdraw_surplus": {
    "at": 306,
    "type": "u8",
    "size": 1
   },
   "is_protocol_withdraw_surplus": {
    "at": 307,
    "type": "u8",
    "size": 1
   },
   "migration_progress": {
    "at": 308,
    "type": "u8",
    "size": 1
   },
   "is_withdraw_leftover": {
    "at": 309,
    "type": "u8",
    "size": 1
   },
   "is_creator_withdraw_surplus": {
    "at": 310,
    "type": "u8",
    "size": 1
   },
   "migration_fee_withdraw_status": {
    "at": 311,
    "type": "u8",
    "size": 1
   },
   "metrics.total_protocol_base_fee": {
    "at": 312,
    "type": "u64",
    "size": 8
   },
   "metrics.total_protocol_quote_fee": {
    "at": 320,
    "type": "u64",
    "size": 8
   },
   "metrics.total_trading_base_fee": {
    "at": 328,
    "type": "u64",
    "size": 8
   },
   "metrics.total_trading_quote_fee": {
    "at": 336,
    "type": "u64",
    "size": 8
   },
   "finish_curve_timestamp": {
    "at": 344,
    "type": "u64",
    "size": 8
   },
   "creator_base_fee": {
    "at": 352,
    "type": "u64",
    "size": 8
   },
   "creator_quote_fee": {
    "at": 360,
    "type": "u64",
    "size": 8
   },
   "legacy_creation_fee_bits": {
    "at": 368,
    "type": "u8",
    "size": 1
   },
   "creation_fee_bits": {
    "at": 369,
    "type": "u8",
    "size": 1
   },
   "has_swap": {
    "at": 370,
    "type": "u8",
    "size": 1
   },
   "_padding_0": {
    "at": 371,
    "type": "u8",
    "size": 1,
    "count": 5
   },
   "protocol_liquidity_migration_fee_bps": {
    "at": 376,
    "type": "u16",
    "size": 2
   },
   "_padding_1": {
    "at": 378,
    "type": "u8",
    "size": 1,
    "count": 6
   },
   "protocol_migration_base_fee_amount": {
    "at": 384,
    "type": "u64",
    "size": 8
   },
   "protocol_migration_quote_fee_amount": {
    "at": 392,
    "type": "u64",
    "size": 8
   },
   "_padding_2": {
    "at": 400,
    "type": "u64",
    "size": 8,
    "count": 3
   }
  }
 },
 "PoolConfig": {
  "discriminator": [
   26,
   108,
   14,
   123,
   116,
   230,
   129,
   43
  ],
  "size": 1048,
  "fields": {
   "quote_mint": {
    "at": 8,
    "type": "pubkey",
    "size": 32
   },
   "fee_claimer": {
    "at": 40,
    "type": "pubkey",
    "size": 32
   },
   "leftover_receiver": {
    "at": 72,
    "type": "pubkey",
    "size": 32
   },
   "pool_fees.base_fee.cliff_fee_numerator": {
    "at": 104,
    "type": "u64",
    "size": 8
   },
   "pool_fees.base_fee.second_factor": {
    "at": 112,
    "type": "u64",
    "size": 8
   },
   "pool_fees.base_fee.third_factor": {
    "at": 120,
    "type": "u64",
    "size": 8
   },
   "pool_fees.base_fee.first_factor": {
    "at": 128,
    "type": "u16",
    "size": 2
   },
   "pool_fees.base_fee.base_fee_mode": {
    "at": 130,
    "type": "u8",
    "size": 1
   },
   "pool_fees.base_fee.padding_0": {
    "at": 131,
    "type": "u8",
    "size": 1,
    "count": 5
   },
   "pool_fees.dynamic_fee.initialized": {
    "at": 136,
    "type": "u8",
    "size": 1
   },
   "pool_fees.dynamic_fee.padding": {
    "at": 137,
    "type": "u8",
    "size": 1,
    "count": 7
   },
   "pool_fees.dynamic_fee.max_volatility_accumulator": {
    "at": 144,
    "type": "u32",
    "size": 4
   },
   "pool_fees.dynamic_fee.variable_fee_control": {
    "at": 148,
    "type": "u32",
    "size": 4
   },
   "pool_fees.dynamic_fee.bin_step": {
    "at": 152,
    "type": "u16",
    "size": 2
   },
   "pool_fees.dynamic_fee.filter_period": {
    "at": 154,
    "type": "u16",
    "size": 2
   },
   "pool_fees.dynamic_fee.decay_period": {
    "at": 156,
    "type": "u16",
    "size": 2
   },
   "pool_fees.dynamic_fee.reduction_factor": {
    "at": 158,
    "type": "u16",
    "size": 2
   },
   "pool_fees.dynamic_fee.padding2": {
    "at": 160,
    "type": "u8",
    "size": 1,
    "count": 8
   },
   "pool_fees.dynamic_fee.bin_step_u128": {
    "at": 168,
    "type": "u128",
    "size": 16
   },
   "partner_liquidity_vesting_info.is_initialized": {
    "at": 184,
    "type": "u8",
    "size": 1
   },
   "partner_liquidity_vesting_info.vesting_percentage": {
    "at": 185,
    "type": "u8",
    "size": 1
   },
   "partner_liquidity_vesting_info._padding": {
    "at": 186,
    "type": "u8",
    "size": 1,
    "count": 2
   },
   "partner_liquidity_vesting_info.bps_per_period": {
    "at": 188,
    "type": "u16",
    "size": 2
   },
   "partner_liquidity_vesting_info.number_of_periods": {
    "at": 190,
    "type": "u16",
    "size": 2
   },
   "partner_liquidity_vesting_info.frequency": {
    "at": 192,
    "type": "u32",
    "size": 4
   },
   "partner_liquidity_vesting_info.cliff_duration_from_migration_time": {
    "at": 196,
    "type": "u32",
    "size": 4
   },
   "creator_liquidity_vesting_info.is_initialized": {
    "at": 200,
    "type": "u8",
    "size": 1
   },
   "creator_liquidity_vesting_info.vesting_percentage": {
    "at": 201,
    "type": "u8",
    "size": 1
   },
   "creator_liquidity_vesting_info._padding": {
    "at": 202,
    "type": "u8",
    "size": 1,
    "count": 2
   },
   "creator_liquidity_vesting_info.bps_per_period": {
    "at": 204,
    "type": "u16",
    "size": 2
   },
   "creator_liquidity_vesting_info.number_of_periods": {
    "at": 206,
    "type": "u16",
    "size": 2
   },
   "creator_liquidity_vesting_info.frequency": {
    "at": 208,
    "type": "u32",
    "size": 4
   },
   "creator_liquidity_vesting_info.cliff_duration_from_migration_time": {
    "at": 212,
    "type": "u32",
    "size": 4
   },
   "padding_0": {
    "at": 216,
    "type": "u8",
    "size": 1,
    "count": 14
   },
   "padding_1": {
    "at": 230,
    "type": "u16",
    "size": 2
   },
   "collect_fee_mode": {
    "at": 232,
    "type": "u8",
    "size": 1
   },
   "migration_option": {
    "at": 233,
    "type": "u8",
    "size": 1
   },
   "activation_type": {
    "at": 234,
    "type": "u8",
    "size": 1
   },
   "token_decimal": {
    "at": 235,
    "type": "u8",
    "size": 1
   },
   "version": {
    "at": 236,
    "type": "u8",
    "size": 1
   },
   "token_type": {
    "at": 237,
    "type": "u8",
    "size": 1
   },
   "quote_token_flag": {
    "at": 238,
    "type": "u8",
    "size": 1
   },
   "partner_permanent_locked_liquidity_percentage": {
    "at": 239,
    "type": "u8",
    "size": 1
   },
   "partner_liquidity_percentage": {
    "at": 240,
    "type": "u8",
    "size": 1
   },
   "creator_permanent_locked_liquidity_percentage": {
    "at": 241,
    "type": "u8",
    "size": 1
   },
   "creator_liquidity_percentage": {
    "at": 242,
    "type": "u8",
    "size": 1
   },
   "migration_fee_option": {
    "at": 243,
    "type": "u8",
    "size": 1
   },
   "fixed_token_supply_flag": {
    "at": 244,
    "type": "u8",
    "size": 1
   },
   "creator_trading_fee_percentage": {
    "at": 245,
    "type": "u8",
    "size": 1
   },
   "token_update_authority": {
    "at": 246,
    "type": "u8",
    "size": 1
   },
   "migration_fee_percentage": {
    "at": 247,
    "type": "u8",
    "size": 1
   },
   "creator_migration_fee_percentage": {
    "at": 248,
    "type": "u8",
    "size": 1
   },
   "padding_2": {
    "at": 249,
    "type": "u8",
    "size": 1,
    "count": 7
   },
   "swap_base_amount": {
    "at": 256,
    "type": "u64",
    "size": 8
   },
   "migration_quote_threshold": {
    "at": 264,
    "type": "u64",
    "size": 8
   },
   "migration_base_threshold": {
    "at": 272,
    "type": "u64",
    "size": 8
   },
   "migration_sqrt_price": {
    "at": 280,
    "type": "u128",
    "size": 16
   },
   "locked_vesting_config.amount_per_period": {
    "at": 296,
    "type": "u64",
    "size": 8
   },
   "locked_vesting_config.cliff_duration_from_migration_time": {
    "at": 304,
    "type": "u64",
    "size": 8
   },
   "locked_vesting_config.frequency": {
    "at": 312,
    "type": "u64",
    "size": 8
   },
   "locked_vesting_config.number_of_period": {
    "at": 320,
    "type": "u64",
    "size": 8
   },
   "locked_vesting_config.cliff_unlock_amount": {
    "at": 328,
    "type": "u64",
    "size": 8
   },
   "locked_vesting_config._padding": {
    "at": 336,
    "type": "u64",
    "size": 8
   },
   "pre_migration_token_supply": {
    "at": 344,
    "type": "u64",
    "size": 8
   },
   "post_migration_token_supply": {
    "at": 352,
    "type": "u64",
    "size": 8
   },
   "migrated_collect_fee_mode": {
    "at": 360,
    "type": "u8",
    "size": 1
   },
   "migrated_dynamic_fee": {
    "at": 361,
    "type": "u8",
    "size": 1
   },
   "migrated_pool_fee_bps": {
    "at": 362,
    "type": "u16",
    "size": 2
   },
   "migrated_pool_base_fee_mode": {
    "at": 364,
    "type": "u8",
    "size": 1
   },
   "enable_first_swap_with_min_fee": {
    "at": 365,
    "type": "u8",
    "size": 1
   },
   "migrated_compounding_fee_bps": {
    "at": 366,
    "type": "u16",
    "size": 2
   },
   "pool_creation_fee": {
    "at": 368,
    "type": "u64",
    "size": 8
   },
   "migrated_pool_base_fee_bytes": {
    "at": 376,
    "type": "u8",
    "size": 1,
    "count": 16
   },
   "sqrt_start_price": {
    "at": 392,
    "type": "u128",
    "size": 16
   },
   "curve": {
    "at": 408,
    "type": "LiquidityDistributionConfig",
    "size": 32,
    "count": 20
   },
   "curve[0].sqrt_price": {
    "at": 408,
    "type": "u128",
    "size": 16
   },
   "curve[0].liquidity": {
    "at": 424,
    "type": "u128",
    "size": 16
   },
   "curve[1].sqrt_price": {
    "at": 440,
    "type": "u128",
    "size": 16
   },
   "curve[1].liquidity": {
    "at": 456,
    "type": "u128",
    "size": 16
   },
   "curve[2].sqrt_price": {
    "at": 472,
    "type": "u128",
    "size": 16
   },
   "curve[2].liquidity": {
    "at": 488,
    "type": "u128",
    "size": 16
   },
   "curve[3].sqrt_price": {
    "at": 504,
    "type": "u128",
    "size": 16
   },
   "curve[3].liquidity": {
    "at": 520,
    "type": "u128",
    "size": 16
   },
   "curve[4].sqrt_price": {
    "at": 536,
    "type": "u128",
    "size": 16
   },
   "curve[4].liquidity": {
    "at": 552,
    "type": "u128",
    "size": 16
   },
   "curve[5].sqrt_price": {
    "at": 568,
    "type": "u128",
    "size": 16
   },
   "curve[5].liquidity": {
    "at": 584,
    "type": "u128",
    "size": 16
   },
   "curve[6].sqrt_price": {
    "at": 600,
    "type": "u128",
    "size": 16
   },
   "curve[6].liquidity": {
    "at": 616,
    "type": "u128",
    "size": 16
   },
   "curve[7].sqrt_price": {
    "at": 632,
    "type": "u128",
    "size": 16
   },
   "curve[7].liquidity": {
    "at": 648,
    "type": "u128",
    "size": 16
   },
   "curve[8].sqrt_price": {
    "at": 664,
    "type": "u128",
    "size": 16
   },
   "curve[8].liquidity": {
    "at": 680,
    "type": "u128",
    "size": 16
   },
   "curve[9].sqrt_price": {
    "at": 696,
    "type": "u128",
    "size": 16
   },
   "curve[9].liquidity": {
    "at": 712,
    "type": "u128",
    "size": 16
   },
   "curve[10].sqrt_price": {
    "at": 728,
    "type": "u128",
    "size": 16
   },
   "curve[10].liquidity": {
    "at": 744,
    "type": "u128",
    "size": 16
   },
   "curve[11].sqrt_price": {
    "at": 760,
    "type": "u128",
    "size": 16
   },
   "curve[11].liquidity": {
    "at": 776,
    "type": "u128",
    "size": 16
   },
   "curve[12].sqrt_price": {
    "at": 792,
    "type": "u128",
    "size": 16
   },
   "curve[12].liquidity": {
    "at": 808,
    "type": "u128",
    "size": 16
   },
   "curve[13].sqrt_price": {
    "at": 824,
    "type": "u128",
    "size": 16
   },
   "curve[13].liquidity": {
    "at": 840,
    "type": "u128",
    "size": 16
   },
   "curve[14].sqrt_price": {
    "at": 856,
    "type": "u128",
    "size": 16
   },
   "curve[14].liquidity": {
    "at": 872,
    "type": "u128",
    "size": 16
   },
   "curve[15].sqrt_price": {
    "at": 888,
    "type": "u128",
    "size": 16
   },
   "curve[15].liquidity": {
    "at": 904,
    "type": "u128",
    "size": 16
   },
   "curve[16].sqrt_price": {
    "at": 920,
    "type": "u128",
    "size": 16
   },
   "curve[16].liquidity": {
    "at": 936,
    "type": "u128",
    "size": 16
   },
   "curve[17].sqrt_price": {
    "at": 952,
    "type": "u128",
    "size": 16
   },
   "curve[17].liquidity": {
    "at": 968,
    "type": "u128",
    "size": 16
   },
   "curve[18].sqrt_price": {
    "at": 984,
    "type": "u128",
    "size": 16
   },
   "curve[18].liquidity": {
    "at": 1000,
    "type": "u128",
    "size": 16
   },
   "curve[19].sqrt_price": {
    "at": 1016,
    "type": "u128",
    "size": 16
   },
   "curve[19].liquidity": {
    "at": 1032,
    "type": "u128",
    "size": 16
   }
  }
 },
 "constants": {
  "APPROVAL_MAX_SECS": "2592000",
  "COIN_DECIMALS": "6",
  "COIN_SUPPLY_RAW": "1000000000000000",
  "FEE_RECIPIENT": "13qRam63xqqd8KNUoAmHWQu7ro71oHqEsYHYaG5MsRiN",
  "MAX_LEFTOVER_RAW": "1000000000",
  "MAX_MIGRATED_POOL_FEE_BPS": "200",
  "MAX_NAME_LEN": "32",
  "MAX_POOL_CREATION_FEE_LAMPORTS": "500000000",
  "MAX_QUOTE_DECIMALS": "9",
  "MAX_SYMBOL_LEN": "10",
  "MAX_TRADE_FEE_NUMERATOR": "20000000",
  "METADATA_URI_PREFIX": "https://vicinity.city/coin-meta/",
  "MIN_QUOTE_DECIMALS": "6",
  "PAYOUT_COOLDOWN_SECS": "86400",
  "REQUIRED_CREATOR_FEE_PERCENT": "50",
  "REQUIRED_CREATOR_LOCKED_LP_PERCENT": "50",
  "REQUIRED_PARTNER_LOCKED_LP_PERCENT": "50"
 },
 "dbcErrors": {
  "6000": "MathOverflow",
  "6001": "InvalidFee",
  "6002": "ExceededSlippage",
  "6003": "ExceedMaxFeeBps",
  "6004": "InvalidAdmin",
  "6005": "AmountIsZero",
  "6006": "TypeCastFailed",
  "6007": "InvalidActivationType",
  "6008": "InvalidQuoteMint",
  "6009": "InvalidCollectFeeMode",
  "6010": "InvalidMigrationFeeOption",
  "6011": "InvalidInput",
  "6012": "NotEnoughLiquidity",
  "6013": "PoolIsCompleted",
  "6014": "PoolIsIncompleted",
  "6015": "InvalidMigrationOption",
  "6016": "InvalidTokenDecimals",
  "6017": "InvalidTokenType",
  "6018": "InvalidFeePercentage",
  "6019": "InvalidQuoteThreshold",
  "6020": "InvalidTokenSupply",
  "6021": "InvalidCurve",
  "6022": "NotPermitToDoThisAction",
  "6023": "InvalidOwnerAccount",
  "6024": "InvalidConfigAccount",
  "6025": "SurplusHasBeenWithdraw",
  "6026": "LeftoverHasBeenWithdraw",
  "6027": "TotalBaseTokenExceedMaxSupply",
  "6028": "UnsupportNativeMintToken2022",
  "6029": "InsufficientLiquidityForMigration",
  "6030": "MissingPoolConfigInRemainingAccount",
  "6031": "InvalidVestingParameters",
  "6032": "InvalidLeftoverAddress",
  "6033": "InsufficientLiquidity",
  "6034": "InvalidFeeScheduler",
  "6035": "InvalidCreatorTradingFeePercentage",
  "6036": "InvalidNewCreator",
  "6037": "InvalidTokenAuthorityOption",
  "6038": "InvalidAccount",
  "6039": "InvalidMigratorFeePercentage",
  "6040": "MigrationFeeHasBeenWithdraw",
  "6041": "InvalidBaseFeeMode",
  "6042": "InvalidFeeRateLimiter",
  "6043": "FailToValidateSingleSwapInstruction",
  "6044": "InvalidMigratedPoolFee",
  "6045": "UndeterminedError",
  "6046": "RateLimiterNotSupported",
  "6047": "AmountLeftIsNotZero",
  "6048": "NextSqrtPriceIsSmallerThanStartSqrtPrice",
  "6049": "InvalidMinBaseFee",
  "6050": "AccountInvariantViolation",
  "6051": "InvalidPoolCreationFee",
  "6052": "PoolCreationFeeHasBeenClaimed",
  "6053": "Unauthorized",
  "6054": "ZeroPoolCreationFee",
  "6055": "InvalidMigrationLockedLiquidity",
  "6056": "InvalidFeeMarketCapScheduler",
  "6057": "FirstSwapValidationFailed",
  "6058": "IncorrectATA",
  "6059": "InsufficientPoolLamports",
  "6060": "InvalidPermission",
  "6061": "InvalidWithdrawProtocolFeeZapAccounts",
  "6062": "MintRestrictedFromZap",
  "6063": "InvalidZapOutParameters",
  "6064": "CpiDisabled",
  "6065": "MissingZapOutInstruction",
  "6066": "InvalidZapAccounts",
  "6067": "InvalidCompoundingParameters",
  "6068": "InvalidClaimProtocolFeeAccounts",
  "6069": "InvalidInstructionsSysvar",
  "6070": "InvalidRemainingAccountsLength",
  "6071": "MissingRemainingAccountForTransferHook",
  "6072": "NoTransferHookProgram",
  "6073": "DuplicatedRemainingAccountTypes",
  "6074": "InvalidTransferHookProgram",
  "6075": "InvalidPoolAccount",
  "6076": "PoolTypeMismatch",
  "6077": "InvalidRemainingAccountSliceType",
  "6078": "DeprecatedBaseFeeMode",
  "6079": "CannotCreateTokenBadgeOnSupportedMint",
  "6080": "InvalidTokenBadge",
  "6081": "QuoteMintHasNonZeroTransferFee",
  "6082": "DeprecatedMigrationOption"
 },
 "launchpadErrors": {
  "6000": "Unauthorized",
  "6001": "NotUpgradeAuthority",
  "6002": "InvalidAddress",
  "6003": "NoPendingAdmin",
  "6004": "NotPendingAdmin",
  "6005": "LaunchesPaused",
  "6006": "PayoutsPaused",
  "6007": "PayoutsNotConfigured",
  "6008": "PayoutKeyNotSeparate",
  "6009": "LaunchConfigDisabled",
  "6010": "LaunchConfigMismatch",
  "6011": "QuoteMintNotAllowed",
  "6012": "ConfigFeeClaimer",
  "6013": "ConfigLeftoverReceiver",
  "6014": "ConfigTokenType",
  "6015": "ConfigDecimalsOrSupply",
  "6016": "ConfigCollectFeeMode",
  "6017": "ConfigFee",
  "6018": "ConfigFeeSplit",
  "6019": "ConfigMetadataMutable",
  "6020": "ConfigLiquidityLock",
  "6021": "ConfigMigration",
  "6022": "ConfigMigrationFee",
  "6023": "ConfigVesting",
  "6024": "ConfigLaunchFee",
  "6025": "BadName",
  "6026": "BadSymbol",
  "6027": "BadExpiry",
  "6028": "ApprovalExpired",
  "6029": "CoinAlreadyLaunched",
  "6030": "WrongFounder",
  "6031": "PoolCreatorMismatch",
  "6032": "WrongPool",
  "6033": "WrongPosition",
  "6034": "WrongRewardsConfig",
  "6035": "WrongRewardsVault",
  "6036": "DestinationMismatch",
  "6037": "OptInFounderMismatch",
  "6038": "PayoutTooSoon",
  "6039": "MathOverflow",
  "6040": "ConfigLeftover"
 }
};
